export const FETCH_MEALS = "FETCH_MEALS";
export const FILTER_MEALS = "FILTER_MEALS";
export const ERROR_MEALS = "ERROR_MEALS";
export const LOADING_MEALS = "LOADING_MEALS";

export const FETCH_MEAL = "FETCH_MEAL";
export const ERROR_MEAL = "ERROR_MEAL";
export const LOADING_MEAL = "LOADING_MEAL";

export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";
export const ERROR_INGREDIENTS = "ERROR_INGREDIENTS";
export const LOADING_INGREDIENTS = "LOADING_INGREDIENTS";
export const FILTER_INGREDIENTS = "FILTER_INGREDIENTS";
export const SEARCH_TERM = "SEARCH_TERM";

export const FETCH_RECIPES_BY_INGREDIENT = "FETCH_RECIPES_BY_INGREDIENT";
export const ERROR_RECIPES_BY_INGREDIENT = "ERROR_RECIPES_BY_INGREDIENT";
export const LOADING_RECIPES_BY_INGREDIENT = "LOADING_RECIPES_BY_INGREDIENT";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const ERROR_CATEGORIES = "ERROR_CATEGORIES";
export const LOADING_CATEGORIES = "LOADING_CATEGORIES";