export {default as Navbar} from './Navbar/Navbar'
export {default as Home} from './Home/Home'
export {default as Categories} from './Categories/Categories'
export {default as Footer} from './Footer/Footer'
export {default as Ingredients} from './Ingredients/Ingredients'